apiVersion: v1
kind: Service
metadata:
  name: tutuplapak-app
  namespace: kube-tutuplapak
spec:
  selector:
    app: tutuplapak-app
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutuplapak-app
  namespace: kube-tutuplapak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutuplapak-app
  template:
    metadata:
      labels:
        app: tutuplapak-app
    spec:
      containers:
        - name: app
          image: tutuplapak:v1     # image yang sudah di-import ke k3s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secrets
          readinessProbe:
            httpGet:
              path: /api/v1/health-check
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health-check
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
